### ISSUE TITLE
HAProxy configuration improvments in Kubernetes context to fix DNS issues

### ISSUE THREAD

**Issue by fkocik** [yanivbhemo/haproxy-redis#1]
Hi Yaniv,

First of all, I want to thank you very much for your excellent post (https://yaniv-bhemo.medium.com/how-to-setup-haproxy-for-redis-sentinel-on-kubernetes-37ee70e44464) that allowed me to workaround **Redis** access problem from outside K8S cluster.

I think your approach is the most elegant solution to this issue : https://github.com/bitnami/charts/issues/3745.

During my tests, I discovered one condition in this solution that causes downtime to the service.
It's related to the DNS dependant approach of the configuration with a tool (**HAProxy**) that performs requests only at startup (https://cbonte.github.io/haproxy-dconv/2.3/configuration.html#5.3). So, if a `pod` is deleted (server restart, drain, etc.), it is never reinjected in the pool until **HAProxy** is restarted.

To workaround the problem, I modified the `haproxy.cfg` file to add a *resolver* section :
```
resolvers k8s
      parse-resolv-conf
      hold other           10s
      hold refused         10s
      hold nx              10s
      hold timeout         10s
      hold valid           10s
      hold obsolete        10s
```

With that tooling in place, we can then rely on the **HAProxy** service discovery features and **Kubernetes** `DNS` conventions (https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#srv-records) to dynamically register backends through `server-template` instruction in *backend* bloc instead of `server` :

```
server-template redis 3 _tcp-redis._tcp.redis-headless.redis.svc.cluster.local:6379 check inter 1s resolvers k8s init-addr none
```
The number of servers in the pool (`3`) is the same value passed to key `replica.replicaCount` of the Redis chart while the service short name (`_tcp-redis`) is the name of the port in generated headless Redis service.

Another cosmetic remark (and that is what I have done in my context) is that you can put the `haproxy.cfg` data in a **ConfigMap** (https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/) :
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
  namespace: redis
data:
  haproxy.cfg: |
    global
      maxconn 1024
    ...
```

Then, in your deployment, you can use the **HAProxy** generally available image (haproxy:2.3) and mount the config through a `configMap` volume (https://kubernetes.io/docs/concepts/storage/volumes/#configmap).

In pod spec :
```
volumes:
  - name: config
    configMap:
      name: haproxy-config
```

In container object :
```
volumeMounts:
  - name: config
    mountPath: /usr/local/etc/haproxy/haproxy.cfg
    subPath: haproxy.cfg
    readOnly: true
```

With this manifest, you don't need to build a custom image anymore and make a generic and configurable solution that could be offered to Bitnami community I guess.

Best Regards.
